### PR TITLE
feat: add new illustrations for Svipper

### PR DESCRIPTION
**Pull request by adriansberg**
These illustrations have been updated for Troms:
- EmptyIllustration
- HoldingHands
- NoFavouriteDeparture
- TicketTilted

Should check that the new illustrations have the same sizes as the old ones. Had to resize a couple of them so they were not too big. Ideally they should probably be contained by a container with the proper size of where it's used, making it more flexible.

Fixes https://github.com/AtB-AS/kundevendt/issues/18263

### CODE REVIEW

**Review by mortennordseth — COMMENTED** [review]
What about these SVGs? 
- Crash and CrashSmall
- TikcetSplash

I thought the onboarding SVGs were in use as well, but couldn't see from a quick search, do you know?

**Comment by adriansberg** [comment]
TicketSplash seems to be used on these views:

- Ticketing_NotEnabledScreen
- UpgradeSplash
- TicketAssistant_WelcomeScreen

Crash seems to be used on this view:

- FullScreenErrorView

CrashSmall seems to be used on this view:

- NoTravelTokenInfo


I could not see a new illustration for either of these in the Figma file however. Have you seen any?

**Comment by mortennordseth** [comment]
> I could not see a new illustration for either of these in the Figma file however. Have you seen any?

It would be best if you asked the PO what they would like to use

**Comment by adriansberg** [comment]
Troms does not have any alternatives for `Crash` and `CrashSmall` yet. Adding `TicketSplash`.

**Comment by mortennordseth** [comment]
> Should check that the new illustrations have the same sizes as the old ones. 

Is this tested? 🤔 I see that some, e.g. EmptyIllustration, is quite different from the replaced one

image

**Comment by adriansberg** [comment]
> Is this tested? 🤔

Yes, but please do, might have missed some.


From description:
>  Ideally they should probably be contained by a container with the proper size of where it's used, making it more flexible.

The main place this is used at the moment is in planner-web, which looks okay.

image

**Pull request merged**
