### PR TITLE
Fix colors for FRAM travelcard and travel planning

### PR DESCRIPTION
**Pull request by adriansberg**

### CODE REVIEW

**Comment by adriansberg** [comment]
The new colors for the travelcard illustration might not match well with the background color where it's used in the webshop. Do you know, @mortennordseth?

**Comment by mortennordseth** [comment]
> The new colors for the travelcard illustration might not match well with the background color where it's used in the webshop. Do you know, @mortennordseth?

Not sure how it will look. Should probably do a test with `yarn link` before merging this. I think the background color where this illustration is used is #0d6569.

**Comment by adriansberg** [comment]
I'll make a quick test in Figma with that color code.

**Comment by adriansberg** [comment]
image

Both of the new versions works pretty well with the background color.

**Pull request merged**
