### PR TITLE
feat: org specific DeparturesOnboarding.svg

### PR DESCRIPTION
**Pull request by toretefre**
For NFK this image on DeparturesOnboarding should be replaced:

image

by

DeparturesOnboarding

### CODE REVIEW

**Comment by toretefre** [comment]
I guess there isn't anyway to reduce the filesize of the NFK svg more, @mikaelbr? 

I tried running it through [svgomg](https://jakearchibald.github.io/svgomg/), but I couldn't get it to look as the AtB svg with only paths. Did I miss an option or something?

This [message](https://mittatb.slack.com/archives/C02EEG7D8EL/p1643366659130939?thread_ts=1643289333.221200&cid=C02EEG7D8EL) also did not help 🙃

**Comment by mikaelbr** [comment]
Problem seems to be that the SVG isn't an SVG but an image embedded in a SVG. Might be due to someone pasting a raster image in Figma and exporting that - or it might be that it is exported wrong. My money on the first case. In that case we're not able to use it in React Native in either case I belive 🤔 It needs to be proper SVG all the way through.

**Comment by mikaelbr** [comment]
(You can see it in the source code of the svg)

**Comment by toretefre** [comment]
Yep, saw that the image was present in the SVG code. Makes sense, will check with the guy who created it (😬)!

**Comment by toretefre** [comment]
> My money on the first case.

The imposter at the department of illustration art confessed everything when presented with the charges. Luckily he was able to fix it by editing a Figma frame, instead of using an actual screenshot. Think it should be better now.

**Comment by mikaelbr** [comment]
Hmm. What is changed on the AtB file? 🤔

**Comment by toretefre** [comment]
I guess you're talking about it being renamed, as it previously was a common file but now is placed in the AtB folder (and FRAM folder as well)?

**Comment by mikaelbr** [comment]
Ah, ok. That explains it. So no breaking change then!

**Review by mikaelbr — APPROVED** [review]

**Comment by toretefre** [comment]
Shouldn't be, just needed to add it to all orgs as it was common before!

**Pull request merged**
