### PR TITLE
feat: Add Checkmark.svg

### PR DESCRIPTION
**Pull request by jorelosorio**
Part of https://github.com/AtB-AS/kundevendt/issues/15878

### CODE REVIEW

**Review by gorandalum — COMMENTED** [review]
If the background color of this illustration is ment to reference the AtB theme, then there needs to be added variations for NfK and Fram as well.

**Comment by jorelosorio** [comment]
> If the background color of this illustration is ment to reference the AtB theme, then there needs to be added variations for NfK and Fram as well.

I also saw other SVG like this in commons.

image


@oyvindmikkelsenatb any comments?

**Comment by gorandalum** [comment]
Note that it is possible to create the circle by code using colors from design-system, and place the check mark mono icon in the middle.

**Comment by jorelosorio** [comment]
> Note that it is possible to create the circle by code using colors from design-system, and place the check mark mono icon in the middle.

I was trying to do make this in the same way as I saw that was used before, for instance the screenshot I sent, I found also another file:

image

As you see In that case it was possible to use the design system colours, use an icon for a checkmark over the background, etc... but it was not made like that. Also is in the commons, somehow I guess is show like that to other orgs.

**Comment by jorelosorio** [comment]
> > Note that it is possible to create the circle by code using colors from design-system, and place the check mark mono icon in the middle.
> 
> I was trying to do make this in the same way as I saw that was used before, for instance the screenshot I sent, I found also another file:
> 
> image
> As you see In that case it was possible to use the design system colours, use an icon for a checkmark over the background, etc... but it was not made like that. Also is in the commons, somehow I guess is show like that to other orgs or might not being used at all. So I was trying to follow the same.

I am going to have a look with the designer. Closing it for now while we agree how it should look. Thanks for the feedback :)

**Comment by marius-at-atb** [comment]
I see that this checkmark was implemented once before [in this file](https://github.com/AtB-AS/mittatb-app/blob/master/src/stacks-hierarchy/Root_ParkingViolationsReporting/Root_ParkingViolationsConfirmationScreen.tsx#L42C4-L51)

**Pull request closed without merging**
