### PR TITLE
feat: new theme for FRAM

### PR DESCRIPTION
**Pull request by mortennordseth**
Updated colors for FRAM and new background illustrations. 

It would be nice if some of you can pull this and test it locally as well (app and webshop). For the webshop you can use this branch for testing as it has some necessary adjustments: https://github.com/AtB-AS/webshop2/pull/349

Closes https://github.com/AtB-AS/kundevendt/issues/4002

### CODE REVIEW

**Comment by toretefre** [comment]
Potentially easier to test following release? React-native and linking of the design system isn't my favourite 😄

**Comment by mortennordseth** [comment]
I can see that 😅 My thought was that it could potentially be a few unnecessary releases if you guys didn't test as well. Might not be an issue though. 

As you don't have to do any changes, just check that everything is okay, it is kind of quick to set up though. Check out this branch, run `yarn build-all` and move the lib folder in `/packages/theme/` to `node_modules/@atb-as/theme`

**Comment by adriansberg** [comment]
Sorry for late response on this. Most of it looks very good. Adding a list of remarks below.



- IMO the "active" color for the nav bar in dark mode is a bit too bright and not very visible. Might be due to seeing it in an emulator though:

image

- Are we going to use the BackgroundIllustration in the app? Along the lines of how AtB has a simple wave.
- The number when selecting the number of travellers seems to have a bit too low contrast in dark mode. The text should probably be white instead of black:
image
- Same as the previous point:
image

- A tad low contrast on the radio buttons in dark mode:
image

**Comment by mortennordseth** [comment]
> * IMO the "active" color for the nav bar in dark mode is a bit too bright and not very visible. Might be due to seeing it in an emulator though:

Julia and I tried to find a color with better contrast, but we couldn't find one. I agree that it is a bit bright, but it's valid in regard to WCAG. 

> * Are we going to use the BackgroundIllustration in the app? Along the lines of how AtB has a simple wave.

I'll add it and see how it looks. I think it's a good idea!

> * The number when selecting the number of travelers seems to have a bit too low contrast in dark mode. The text should probably be white instead of black:
> * Same as the previous point:

I kind of agree, but this is actually good. 6.8 AA, while white fails AA. 

> * A tad low contrast on the radio buttons in dark mode:

I agree. I see that the color "background accent 3" is used for the checkbox. Should probably be one of the interactive colors 🤔 I'll take a look at how we can solve this

**Review by adriansberg — APPROVED** [review]
Added some rem

**Pull request merged**
