### PR TITLE
Update colors of images for FRAM

### PR DESCRIPTION
**Pull request by adriansberg**
Onboarding images needed to be a different color to get a better contrast with the grey background.
NoFavouriteDeparture needed to be different in light mode vs dark mode. That means that it also has to be added to dark/light folder for AtB and NFK as well, so that the themed component will work correctly.

Partly fixes https://github.com/AtB-AS/kundevendt/issues/3773

### CODE REVIEW

**Comment by adriansberg** [comment]
@mikaelbr this is possibly a breaking change, since an asset changes its path, how do we handle that when publishing etc.?

**Comment by mikaelbr** [comment]
The output of the assets doesn't change path, or? Is the "API" actually different?

**Comment by mikaelbr** [comment]
Honestly, can't remember the details right now. But doesn't it also get included as a non-dark mode? no? maybe that was the different type of dark mode 😅

**Comment by mortennordseth** [comment]
Yes, I believe this is a breaking change. Currently, the `NoFavouriteDeparture.svg` is imported as 
`import {NoFavouriteDeparture} from '@atb/assets/svg/color/images/';` and with this change, it needs to change to 
 `import {NoFavouriteDeparture} from '@atb/assets/svg/color/images/dark/';` (or light).
 
Or is this handled in some way that I don't see? 🤔 

See https://github.com/AtB-AS/mittatb-app/blob/9f9eb685447ab4af53493898deab952c36d2a171/src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/DeparturesWidget.tsx#L3

**Comment by mortennordseth** [comment]
I did the same with `TravelPlanning.svg` for v6.0.0 and when this version was used in the app we had to update the path due to an error. See https://github.com/AtB-AS/mittatb-app/pull/3355

**Comment by adriansberg** [comment]
Okay. So when publishing I'll have to bump the major and not the minor. 👍

**Comment by mikaelbr** [comment]
Yes

**Pull request merged**
